location          = "ap-south-1"
rg                = "monday_rg"
app_name          = "monday_app"
source_ip         = "0.0.0.0/0"
ec2_ami_id        = "ami-0851b76e8b1bce90b"
ec2_instance_type = "t2.nano"